---
- name: ensure apt cache is up to date
  apt:
    update_cache=yes
    cache_valid_time=3600

- name: install postgresql
  apt: name={{item}}
  with_items:
    - postgresql
    - python-psycopg2

- name: ensure database is created
  sudo_user: postgres
  postgresql_db:
    name={{dbname}}

- name: ensure user has access to database
  sudo_user: postgres
  postgresql_user:
    db={{dbname}}
    name={{dbuser}}
    password="{{dbpassword}}"
    priv=ALL
    role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: postgres should listen on all hosts
  lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf regexp='^listen_addresses' line="listen_addresses = '*'"

- name: allow host to auth on guest postgres
  lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf regexp='^host\s+all\s+all\s+samenet' line='host all all samenet md5'

- service: name=postgresql state=restarted
